name: backend

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:8080
    env_file:
      - .env.dev

  db:
    image: postgres
    env_file:
      - .env.dev
    ports:
      - 5432:5432
