basePath: /api/v1/
definitions:
  handlers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.User:
    type: object
host: localhost:8080
info:
  contact: {}
  title: ZLP-LFP API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Обработка запроса на вход пользователя
      operationId: login
      parameters:
      - description: Данные пользователя (email и пароль)
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: Login
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      description: Обработка запроса выход пользователя из системы
      operationId: logout
      produces:
      - application/json
      responses: {}
      summary: Logout
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Обработка запроса на регистрацию пользователя
      operationId: register
      parameters:
      - description: Данные о пользователе
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses: {}
      summary: Register
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
