name: Go CI

on:
  pull_request:
    branches: [ master, dev, draft ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name:
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          cd ./app
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g server.go
          go build -v ./...

      - name: Test
        run: |
          cd ./app
          go test -v ./...
