name: Go CI

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name:
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          cd ./app
          go build -v ./...

      - name: Test
        run: |
          cd ./app
          go test -v ./...
